/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guacha.lab2;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import javax.swing.JTextArea;

/**
 * Interfaz principal que contiene todos las opciones del programa en su totalidad
 * @author Guacha
 */
public class Mapa extends javax.swing.JFrame {
    /**
     * Creates new form Mapa
     */
    
    private final Graphics g;
    private Graphe graphe;
    private Sommet sel;
    
    
    public Mapa() {
        initComponents();
        g = drawPanel.getGraphics();
        this.graphe = new Graphe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        editArete = new javax.swing.JButton();
        sauvegarder = new javax.swing.JButton();
        ouvrir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        drawPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        drawPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drawPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        output.setEditable(false);
        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        editArete.setText("Editar Estación");
        editArete.setEnabled(false);
        editArete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAreteActionPerformed(evt);
            }
        });

        sauvegarder.setText("Guardar mapa");
        sauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauvegarderActionPerformed(evt);
            }
        });

        ouvrir.setText("Cargar mapa");
        ouvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouvrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editArete, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sauvegarder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ouvrir)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editArete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sauvegarder)
                            .addComponent(ouvrir))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
    Operación que se corre cada vez que se hace clic sobre el panel
    encuentra si se hizo clic sobre algún nodo y hace la operación pertinente
    **/
    private void drawPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMouseClicked
        output.setText("");                                         //Limpiamos el output
        Point p = evt.getPoint();                                   //Tipo de dato Point que guarda la posición [X,Y] del punto donde ocurre el evento 
        boolean collide = false;                                    //Boleano que es true si se hizo clic sobre un vértice
        Sommet found = null;                                        //Vértice sobre el que hizo clic (Si existe)
        
        //Ciclo para encontrar un vértice que tenga una posición sobre la que se hizo clic
        for (Sommet sommet : graphe.getSommAdj().keySet()) {        
            if (Math.abs(sommet.pos.distance(p.x, p.y)) < 10) {     //Esta condición revisa todo el radio del nodo y revisa si el clic está en ese radio
                collide = 1 == 1;                                   //1==1: Verdadero
                found = sommet;         
            }
        }
        if (!collide) {                                             //Si no se hizo clic sobre un vertice
            sel = null;
            Connections c = new Connections(graphe, this, evt.getPoint()); //Abre la ventana de cración/Edición de vértices con constructor de creación
            c.setVisible(true);
            dessinerGraphe();
        } else {
            dessinerGraphe(found);
            sel = found;
            showInfo(found);
        }
        setupButtons();
    }//GEN-LAST:event_drawPanelMouseClicked
    
    //Boton guardar
    private void sauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauvegarderActionPerformed
        Ficheur f = new Ficheur();
        f.sauvegarder(graphe); 
    }//GEN-LAST:event_sauvegarderActionPerformed
    
    //Boton Abrir
    private void ouvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouvrirActionPerformed
        Ficheur f = new Ficheur();
        this.graphe = f.ouvrir(); //Carga el grafo de un archivo y lo dibuja
        dessinerGraphe();
    }//GEN-LAST:event_ouvrirActionPerformed
    /**
     * Abre la ventana de conexiones con el constructor para Editar vértices 
     */
    private void editAreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAreteActionPerformed
        if (sel != null) {
            new Connections(graphe, this, sel).setVisible(true);
        }
    }//GEN-LAST:event_editAreteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Mapa().setVisible(true);
        });
    }

   
    /**
     * Función que se encarga de dibujar el grafo en pantalla sobre el panel de dibujo
     */
    public void dessinerGraphe() {
        clearPane(); //Limpiar el panel
        graphe.getSommAdj().entrySet().forEach((entry) -> { //Se busca en el mapa cada combinación de llave-dato (Expresión lambda)
            int x1, y1, x2, y2;                             //Posición inicial-final de la linea y de cada vertice
            x1 = entry.getKey().pos.x;                      //obtener [X,Y] del nodo por graficar
            y1 = entry.getKey().pos.y;
            for (Sommet sommet : entry.getValue().keySet()) {//Se busca en las relaciones de ese nodo
                x2 = sommet.pos.x;                           //Se obtiene las [X,Y] del nodo relacionado y se dibuja la linea y el nodo al final de la linea
                y2 = sommet.pos.y;
                g.setColor(Color.red);
                g.drawLine(x1, y1, x2, y2);
            }
            g.setColor(getColor(entry.getKey()));
            g.fillOval(x1-5, y1-5, 10, 10);
        });
        
    }
    /**
     * Función que Función que se encarga de dibujar el grafo en pantalla sobre el panel de dibujo <p>
     * Esta recibe el parámetro V, que es un nodo "marcado", y a a la hora de dibujarlo, tendrá distinto color
     * @param v El nodo a marcar en el grafo
     */
    public void dessinerGraphe(Sommet v) {
        //Todo es exactamente igual a la función anterior, solo que en la 
        //selección del color, si es el nodo marcado, será verde.
        clearPane();
        graphe.getSommAdj().entrySet().forEach((entry) -> {
            int x1, y1, x2, y2;
            x1 = entry.getKey().pos.x;
            y1 = entry.getKey().pos.y;
            
            for (Sommet sommet : entry.getValue().keySet()) {
                x2 = sommet.pos.x;
                y2 = sommet.pos.y;
                g.setColor(Color.red);
                g.drawLine(x1, y1, x2, y2);
            }
            if (entry.getKey().equals(v)) {
                g.setColor(Color.green);
            } else {
                g.setColor(getColor(entry.getKey()));
            }
            g.fillOval(x1-5, y1-5, 10, 10);
        });
    }
    
    /**
     * Función que limpia el panel completo.<p>
     * En realidad, crea un cuadrado de 1000x1000 empezando en [0,0] en blanco
     */
    private void clearPane() {
        g.clearRect(0, 0, 1000, 1000);
    }
    
    
    /**
     * Retorna un color dependiendo del tipo de estación que teng aun vértice
     * @param s El vértice para el que se quiere hallar el color
     * @return el color con el que dse va a dibujar el vértice
     */
    private Color getColor(Sommet s) {
        switch(s.type) {
            case STATION_BUS:
                return Color.BLACK;
            case STATION_METRO:
                return Color.RED;
            case STATION_BUSDENUIT:
                return Color.MAGENTA;
            case STATION_MULTI:
                return Color.ORANGE;
            default:
                return Color.BLACK;
        }
    }
    /**
     * Esta función se encarga de encender o apagar los botones cuando sea necesario
     */
    private void setupButtons() {
        editArete.setEnabled(sel != null);
    }
    
    /**
     * Esta función escribe en el Area de texto la información que se requiere del nodo seleccionado <p>
     * La información es proporcionada por la clase Graphe
     * @param trouve El nodo cuya enformación se va a mostrar
     */
    public void showInfo(Sommet trouve) {
        output.setText("Estación Seleccionada: \n");
        output.append("Nombre: " + trouve.nombre + "\n");
        output.append(graphe.soutGraphe(trouve));
    }

    /**
     * Getter para el TextArea llamado "output" que existe en la ventana principal
     * @return JTextArea "output" de la ventana Mapa
     */
    public JTextArea getOutput() {
        return output;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel drawPanel;
    private javax.swing.JButton editArete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea output;
    private javax.swing.JButton ouvrir;
    private javax.swing.JButton sauvegarder;
    // End of variables declaration//GEN-END:variables
    
    
    
}